### ISSUE TITLE
Umlauts are broken 

### ISSUE THREAD

**Issue by GSI** [mpalmer/jekyll-static-comments#9]
In the resulting email, umlauts are incorrectly displayed.
- ö becomes Ã¶
- ä becomes Ã€
- ü becomes ÃŒ
- ...

I have yet to look at the code, but maybe someone else knows the solution without needing to investigate first.

**Comment by IQAndreas** [comment]
I was able to fix it by adding the following line to `commentsubmit.php` after you have finished adding all the data to the message:

```
$msg=utf8_decode($msg);
```

Would you like me to show you exactly where to place it, or are you familiar enough with PHP to fix it on your own?

EDIT: _I made the changes for you. See the commit mentioned below._

**Comment by GSI** [comment]
@IQAndreas Thanks for the quick fix! It seems to be working fine.

**Comment by GSI** [comment]
Just did another test:

My KMail filter rule sends the email body to some custom commands. In that case only the variant _without_ the utf8_decode() results in correct umlauts in the final files.

This is more important than readability in the mail itself, so I am reverting back to that variant.

**Comment by IQAndreas** [comment]
Okay, try this version. Here I'm explicitly defining the character encoding of the email and subject to be UTF-8.
https://github.com/IQAndreas/jekyll-static-comments/tree/patch-1

Or if you only want a list of the changes made:
https://github.com/IQAndreas/jekyll-static-comments/commit/dd18ae92e25294f49e0b7d33026b0db3ecff0503

The commit includes a minor change to the comment template, which may or may not be necessary. I'm not in a position to test if it works at the moment, so could you give it a try yourself and let me know if it works properly? Otherwise, I'll give it a try tomorrow.

**Comment by IQAndreas** [comment]
Completely separate issue (normally I would ask this via email, but you have none provided in your profile), would your KMail filter have an easier time if it attached the comment to the email as a `yaml` file, rather than scrape it from the email body?

(On a more related note, in my testing, doing this causes characters with umlauts to show up just fine in the resulting text file.)

_EDIT: This discussion has been moved to email._
